apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-prediction
  labels:
    app: flight-price-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-price-prediction
  template:
    metadata:
      labels:
        app: flight-price-prediction
    spec:
      containers:
        - name: flight-price-prediction
          image: navjotkhatri/flight_price_prediction
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: flight-price-prediction
  labels:
    app: flight-price-prediction
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: flight-price-prediction
  type: LoadBalancer
